export const UPDATE_SORT_TYPE = 'app/HomePage/UPDATE_SORT_TYPE';
export const UPDATE_LANGUAGE = 'app/HomePage/UPDATE_LANGUAGE';
export const UPDATE_EXAMPLE = 'app/HomePage/UPDATE_EXAMPLE';
export const UPDATE_SPACE_COMPLEXITY_WORST = 'app/HomePage/UPDATE_SPACE_COMPLEXITY_WORST';
export const UPDATE_TIME_COMPLEXITY_BEST = 'app/HomePage/UPDATE_TIME_COMPLEXITY_BEST';
export const UPDATE_TIME_COMPLEXITY_WORST = 'app/HomePage/UPDATE_TIME_COMPLEXITY_WORST';
